CREATE DATABASE INVENTORY_SYSTEM;
USE INVENTORY_SYSTEM;

CREATE TABLE COMPANY(
	C_ID int primary key,
	C_name nvarchar(50) NOT NULL
);

CREATE TABLE FACTORY (
    F_code int primary key ,
    F_name nvarchar(50) NOT NULL,
    F_address nvarchar(MAX) NOT NULL,
);

CREATE TABLE STORAGE(
	S_number int primary key,
	S_componey_id int NOT NULL foreign key references COMPANY(C_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	S_type nvarchar(50) NOT NULL,
	S_capacity int NOT NULL
);

CREATE TABLE PRODUCT(
	P_ID INT PRIMARY KEY,
	P_name NVARCHAR(70) NOT NULL,
	P_expireDate DATE NOT NULL,
	P_produceDate DATE NOT NULL,
	P_number INT NOT NULL,
	P_type NVARCHAR(50) NOT NULL,
	P_enterDate DATE NOT NULL,
	P_exitDate DATE,
	P_block INT NOT NULL, 
	P_row INT NOT NULL,
	P_column INT NOT NULL,
	P_factory_ID INT NOT NULL FOREIGN KEY REFERENCES FACTORY(F_code) ON DELETE CASCADE ON UPDATE CASCADE,
	P_storage_number INT NOT NULL FOREIGN KEY REFERENCES STORAGE(S_number) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE EMPLOYEE(
	E_code int primary key,
	E_componey_id int  NOT NULL foreign key references COMPANY(C_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	E_name nvarchar(50) NOT NULL,
	E_working_hours nvarchar(50) NOT NULL,
	E_hire_date date NOT NULL
);

CREATE TABLE MANAGER(
	M_code int primary key,
	M_storage_num int NOT NULL foreign key references STORAGE(S_number) ON DELETE CASCADE ON UPDATE CASCADE,
	M_name nvarchar(50) NOT NULL,
	M_working_hours nvarchar(50) NOT NULL,
	M_report nvarchar(max),
	M_report_date date,
	M_hire_date date NOT NULL
);



CREATE TABLE REPAIRMAN(
	R_managerCode INT NOT NULL FOREIGN KEY REFERENCES MANAGER(M_code) ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE KEEPER(
	K_managerCode INT NOT NULL FOREIGN KEY REFERENCES MANAGER(M_code) ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE CODER(
	COD_managerCode INT NOT NULL FOREIGN KEY REFERENCES MANAGER(M_code) ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE SHOPPING_DEMAND_CONTROLLER(
	SDC_managerCode INT NOT NULL FOREIGN KEY REFERENCES MANAGER(M_code) ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE PRODUCT_ARRANGER(
	PA_managerCode INT NOT NULL FOREIGN KEY REFERENCES MANAGER(M_code) ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE INVENTORY_CONTROLLER(
	IC_managerCode INT NOT NULL FOREIGN KEY REFERENCES MANAGER(M_code) ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE WAREHOUSE_KEEPER(
	R_managerCode INT NOT NULL FOREIGN KEY REFERENCES MANAGER(M_code) ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE INSPECTOR(
	INS_managerCode INT NOT NULL FOREIGN KEY REFERENCES MANAGER(M_code) ON DELETE CASCADE ON UPDATE CASCADE,
);

